UndefVarError: `StdFill` not defined MacOS  (#77)
* run ci

* enable tests outside ubuntu

* Revert "enable tests outside ubuntu"

This reverts commit 1bacba2a86e43ccfd1905bd3587dc427627a8059.

* undef ranges

* Update src/openfhe_julia.cpp

---------

Co-authored-by: Michael Schlottke-Lakemper <michael@sloede.com>